# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_erro(object):
    def setupUi(self, erro):
        erro.setObjectName("erro")
        erro.resize(800, 800)
        erro.setMinimumSize(QtCore.QSize(800, 800))
        erro.setMaximumSize(QtCore.QSize(800, 800))
        self.centralwidget = QtWidgets.QWidget(erro)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 801, 841))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("erro.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(170, 190, 511, 431))
        self.back_button.setStyleSheet("background-color:transparent;")
        self.back_button.setText("")
        self.back_button.setObjectName("back_button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 120, 211, 31))
        self.label_2.setStyleSheet("font-size:20px;")
        self.label_2.setObjectName("label_2")
        erro.setCentralWidget(self.centralwidget)

        self.retranslateUi(erro)
        QtCore.QMetaObject.connectSlotsByName(erro)

    def retranslateUi(self, erro):
        _translate = QtCore.QCoreApplication.translate
        erro.setWindowTitle(_translate("erro", "MainWindow"))
        self.label_2.setText(_translate("erro", "Para voltar clique no X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    erro = QtWidgets.QMainWindow()
    ui = Ui_erro()
    ui.setupUi(erro)
    erro.show()
    sys.exit(app.exec_())
