# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_outhome(object):
    def setupUi(self, outhome):
        outhome.setObjectName("outhome")
        outhome.resize(800, 800)
        outhome.setMinimumSize(QtCore.QSize(800, 800))
        outhome.setMaximumSize(QtCore.QSize(800, 800))
        outhome.setStyleSheet("background-color:#EAC800;\n"
"")
        self.centralwidget = QtWidgets.QWidget(outhome)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 240, 801, 431))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgs/1896 1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 801, 241))
        self.label_2.setStyleSheet("background-color:#01D9CB;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 80, 311, 81))
        self.label_3.setStyleSheet("font-size:25px;\n"
"tex-align: center;\n"
"background-color:#27DACE;")
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        outhome.setCentralWidget(self.centralwidget)

        self.retranslateUi(outhome)
        QtCore.QMetaObject.connectSlotsByName(outhome)

    def retranslateUi(self, outhome):
        _translate = QtCore.QCoreApplication.translate
        outhome.setWindowTitle(_translate("outhome", "MainWindow"))
        self.label_3.setText(_translate("outhome", "Parabéns! Agora se divirta!!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    outhome = QtWidgets.QMainWindow()
    ui = Ui_outhome()
    ui.setupUi(outhome)
    outhome.show()
    sys.exit(app.exec_())
