# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fourth.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mirror(object):
    def setupUi(self, mirror):
        mirror.setObjectName("mirror")
        mirror.resize(800, 800)
        mirror.setMinimumSize(QtCore.QSize(800, 800))
        mirror.setMaximumSize(QtCore.QSize(800, 800))
        mirror.setAutoFillBackground(False)
        mirror.setStyleSheet("background-color:#D6C099;")
        self.centralwidget = QtWidgets.QWidget(mirror)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 811, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("espelho.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.mirror_tip = QtWidgets.QLabel(self.centralwidget)
        self.mirror_tip.setGeometry(QtCore.QRect(250, 150, 311, 431))
        self.mirror_tip.setAutoFillBackground(False)
        self.mirror_tip.setStyleSheet("font-size:20px;\n"
"background-color:#6FE2FF;")
        self.mirror_tip.setWordWrap(True)
        self.mirror_tip.setObjectName("mirror_tip")
        self.back_tofirst = QtWidgets.QPushButton(self.centralwidget)
        self.back_tofirst.setGeometry(QtCore.QRect(320, 720, 191, 31))
        self.back_tofirst.setStyleSheet("font-size:15px;\n"
"background-color:#B1AF74;")
        self.back_tofirst.setObjectName("back_tofirst")
        mirror.setCentralWidget(self.centralwidget)

        self.retranslateUi(mirror)
        QtCore.QMetaObject.connectSlotsByName(mirror)

    def retranslateUi(self, mirror):
        _translate = QtCore.QCoreApplication.translate
        mirror.setWindowTitle(_translate("mirror", "MainWindow"))
        self.mirror_tip.setText(_translate("mirror", "A quarta dica é Somente eu brilho!\n"
"Guarde essa letra: L"))
        self.back_tofirst.setText(_translate("mirror", "Volte para a primeira página"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mirror = QtWidgets.QMainWindow()
    ui = Ui_mirror()
    ui.setupUi(mirror)
    mirror.show()
    sys.exit(app.exec_())
