# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lasttip.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shine(object):
    def setupUi(self, shine):
        shine.setObjectName("shine")
        shine.resize(800, 800)
        shine.setMinimumSize(QtCore.QSize(800, 800))
        shine.setMaximumSize(QtCore.QSize(800, 800))
        self.centralwidget = QtWidgets.QWidget(shine)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-60, 0, 861, 801))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("luz.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.dic_letter = QtWidgets.QLabel(self.centralwidget)
        self.dic_letter.setGeometry(QtCore.QRect(160, 450, 781, 171))
        self.dic_letter.setStyleSheet("font-size: 18px;")
        self.dic_letter.setObjectName("dic_letter")
        self.proximapag = QtWidgets.QPushButton(self.centralwidget)
        self.proximapag.setGeometry(QtCore.QRect(190, 20, 361, 341))
        self.proximapag.setText("")
        self.proximapag.setFlat(True)
        self.proximapag.setObjectName("proximapag")
        shine.setCentralWidget(self.centralwidget)

        self.retranslateUi(shine)
        QtCore.QMetaObject.connectSlotsByName(shine)

    def retranslateUi(self, shine):
        _translate = QtCore.QCoreApplication.translate
        shine.setWindowTitle(_translate("shine", "MainWindow"))
        self.dic_letter.setText(_translate("shine", "A última letra é: S. Clique na luz e advinhe onde está a chave.\n"
"Formando a palavra com as letras guardadas."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    shine = QtWidgets.QMainWindow()
    ui = Ui_shine()
    ui.setupUi(shine)
    shine.show()
    sys.exit(app.exec_())
