# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maçaneta.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_key(object):
    def setupUi(self, key):
        key.setObjectName("key")
        key.resize(800, 800)
        key.setMinimumSize(QtCore.QSize(800, 800))
        key.setMaximumSize(QtCore.QSize(800, 800))
        key.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(key)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 80, 381, 421))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("chave.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 630, 771, 51))
        self.label_2.setStyleSheet("font-size:20px;")
        self.label_2.setObjectName("label_2")
        self.out_home = QtWidgets.QPushButton(self.centralwidget)
        self.out_home.setGeometry(QtCore.QRect(280, 80, 231, 391))
        self.out_home.setText("")
        self.out_home.setFlat(True)
        self.out_home.setObjectName("out_home")
        key.setCentralWidget(self.centralwidget)

        self.retranslateUi(key)
        QtCore.QMetaObject.connectSlotsByName(key)

    def retranslateUi(self, key):
        _translate = QtCore.QCoreApplication.translate
        key.setWindowTitle(_translate("key", "MainWindow"))
        self.label_2.setText(_translate("key", "Você encontrou a chave!! toque nela e abra a porta clicando na maçaneta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    key = QtWidgets.QMainWindow()
    ui = Ui_key()
    ui.setupUi(key)
    key.show()
    sys.exit(app.exec_())
