# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'penultimaTela.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_verification(object):
    def setupUi(self, verification):
        verification.setObjectName("verification")
        verification.resize(800, 800)
        verification.setMinimumSize(QtCore.QSize(800, 800))
        verification.setMaximumSize(QtCore.QSize(800, 800))
        self.centralwidget = QtWidgets.QWidget(verification)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 811, 801))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgs/verifica.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.iinput_usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.iinput_usuario.setGeometry(QtCore.QRect(180, 480, 421, 31))
        self.iinput_usuario.setObjectName("iinput_usuario")
        self.validation = QtWidgets.QPushButton(self.centralwidget)
        self.validation.setGeometry(QtCore.QRect(310, 600, 161, 71))
        self.validation.setStyleSheet("font-size: 15px;")
        self.validation.setFlat(True)
        self.validation.setObjectName("validation")
        self.question = QtWidgets.QLabel(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(80, 270, 671, 171))
        self.question.setStyleSheet("font-size: 18px;")
        self.question.setText("")
        self.question.setObjectName("question")
        self.correct_error = QtWidgets.QLabel(self.centralwidget)
        self.correct_error.setGeometry(QtCore.QRect(80, 130, 671, 171))
        self.correct_error.setStyleSheet("font-size: 18px;")
        self.correct_error.setText("")
        self.correct_error.setObjectName("correct_error")
        verification.setCentralWidget(self.centralwidget)

        self.retranslateUi(verification)
        QtCore.QMetaObject.connectSlotsByName(verification)

    def retranslateUi(self, verification):
        _translate = QtCore.QCoreApplication.translate
        verification.setWindowTitle(_translate("verification", "MainWindow"))
        self.validation.setText(_translate("verification", "Enviar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    verification = QtWidgets.QMainWindow()
    ui = Ui_verification()
    ui.setupUi(verification)
    verification.show()
    sys.exit(app.exec_())
