# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'play_error.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_play_error(object):
    def setupUi(self, play_error):
        play_error.setObjectName("play_error")
        play_error.resize(800, 800)
        play_error.setMinimumSize(QtCore.QSize(800, 800))
        play_error.setMaximumSize(QtCore.QSize(800, 800))
        play_error.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(play_error)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 100, 341, 361))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgs/erro.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 80, 211, 31))
        self.label_2.setStyleSheet("font-size:20px;")
        self.label_2.setObjectName("label_2")
        self.back_topage = QtWidgets.QPushButton(self.centralwidget)
        self.back_topage.setGeometry(QtCore.QRect(270, 190, 281, 241))
        self.back_topage.setText("")
        self.back_topage.setFlat(True)
        self.back_topage.setObjectName("back_topage")
        play_error.setCentralWidget(self.centralwidget)

        self.retranslateUi(play_error)
        QtCore.QMetaObject.connectSlotsByName(play_error)

    def retranslateUi(self, play_error):
        _translate = QtCore.QCoreApplication.translate
        play_error.setWindowTitle(_translate("play_error", "MainWindow"))
        self.label_2.setText(_translate("play_error", "Para voltar clique no X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    play_error = QtWidgets.QMainWindow()
    ui = Ui_play_error()
    ui.setupUi(play_error)
    play_error.show()
    sys.exit(app.exec_())
