# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_second(object):
    def setupUi(self, second):
        second.setObjectName("second")
        second.resize(800, 800)
        second.setMinimumSize(QtCore.QSize(800, 800))
        second.setMaximumSize(QtCore.QSize(800, 800))
        second.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(second)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.label.setMinimumSize(QtCore.QSize(800, 800))
        self.label.setMaximumSize(QtCore.QSize(800, 800))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgs/1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 150, 771, 181))
        self.label_2.setStyleSheet("font-size: 18px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 270, 671, 171))
        self.label_3.setStyleSheet("font-size: 18px;")
        self.label_3.setObjectName("label_3")
        self.backfirst = QtWidgets.QPushButton(self.centralwidget)
        self.backfirst.setGeometry(QtCore.QRect(305, 670, 211, 21))
        self.backfirst.setStyleSheet("padding:25px;\n"
"font-size:15px;\n"
"background-color:#B1B175;")
        self.backfirst.setObjectName("backfirst")
        second.setCentralWidget(self.centralwidget)

        self.retranslateUi(second)
        QtCore.QMetaObject.connectSlotsByName(second)

    def retranslateUi(self, second):
        _translate = QtCore.QCoreApplication.translate
        second.setWindowTitle(_translate("second", "MainWindow"))
        self.label_2.setText(_translate("second", "reason fast, according to the result find the next object. \n"
"26, 29, 33, 36, 40 \n"
"What´s the next number? \n"
"1, 54, 43, 50"))
        self.label_3.setText(_translate("second", "\n"
"in this reason fast there are two patterns, what is the second pattern?\n"
"Is an integer value. After thinking, look for the object with that amount."))
        self.backfirst.setText(_translate("second", "Back to first screen"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    second = QtWidgets.QMainWindow()
    ui = Ui_second()
    ui.setupUi(second)
    second.show()
    sys.exit(app.exec_())
