# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_tip.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_table_tip(object):
    def setupUi(self, table_tip):
        table_tip.setObjectName("table_tip")
        table_tip.resize(800, 800)
        table_tip.setMinimumSize(QtCore.QSize(800, 800))
        table_tip.setMaximumSize(QtCore.QSize(800, 800))
        table_tip.setStyleSheet("background-color:#E2E2FD")
        self.centralwidget = QtWidgets.QWidget(table_tip)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 651, 611))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgs/2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 210, 231, 161))
        self.label_2.setStyleSheet("font-size:20px;\n"
"background-color:transparent\n"
"")
        self.label_2.setObjectName("label_2")
        self.back_toinitial = QtWidgets.QPushButton(self.centralwidget)
        self.back_toinitial.setGeometry(QtCore.QRect(140, 150, 801, 401))
        self.back_toinitial.setStyleSheet("background-color:transparent;")
        self.back_toinitial.setText("")
        self.back_toinitial.setObjectName("back_toinitial")
        table_tip.setCentralWidget(self.centralwidget)

        self.retranslateUi(table_tip)
        QtCore.QMetaObject.connectSlotsByName(table_tip)

    def retranslateUi(self, table_tip):
        _translate = QtCore.QCoreApplication.translate
        table_tip.setWindowTitle(_translate("table_tip", "MainWindow"))
        self.label_2.setText(_translate("table_tip", "A palavra começa com P\n"
"e termina com H"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    table_tip = QtWidgets.QMainWindow()
    ui = Ui_table_tip()
    ui.setupUi(table_tip)
    table_tip.show()
    sys.exit(app.exec_())
